### ISSUE TITLE
Jedi Fallen Order results in a 404

### ISSUE THREAD

**Issue by cwhits** [ELowry/StadiaIcons#6]
URL when I click the install a shortcut button:

https://stadiaicons.web.app/ck:impression,hover,click/?fullName=STAR%20WARS%20Jedi%3A%20Fallen%20Order%E2%84%A2

**Comment by cwhits** [comment]
which appears to decode to `STAR WARS Jedi: Fallen Order™`

**Comment by ELowry** [comment]
Hi there!

The issue doesn't seem to be with the name (I just tried with the Immortals Feny Rising demo which has a ™ too), but with the first part of the URL, where instead of the uid (`36c01626f21f428e8d5ae35ce19c774brcp1`) you have `ck:impression,hover,click` for some reason. This might be an issue with an extension?

Just to check, are you creating the icon through https://stadiaicons.web.app or through Stadie Enhanced?
And if you're using Stadia Enhanced do you have the new or "old" Stadia home page? (are there games on the right of the first page)

Finally, you can simply use this link in the meantime :) [https://stadiaicons.web.app/36c01626f21f428e8d5ae35ce19c774brcp1/?fullName=Star%20Wars%20Jedi%20%E2%80%93%20Fallen%20Order&shortName=Star%20Wars%20Jedi](https://stadiaicons.web.app/36c01626f21f428e8d5ae35ce19c774brcp1/?fullName=Star%20Wars%20Jedi%20%E2%80%93%20Fallen%20Order&shortName=Star%20Wars%20Jedi)

**Comment by cwhits** [comment]
Stadia Enhanced with the "new" page.

**Comment by cwhits** [comment]
so, now that you mention it. it is all games. I'm guessing this is an issue with stadia enhanced then?

**Comment by ELowry** [comment]
Yep; I think ChristopherKlay is waiting for the new UI to be rolled out to all before pushing an update (he might not even have the new UI and can't make the changes as a result).

You should be able to keep an eye on things with [this issue](https://github.com/ChristopherKlay/StadiaEnhanced/issues/34) over on the StadiaEnhanced side of things. On my side of things, I'll work with him to help make sure the shortcuts are fixed quickly.

You can always use the default StadiaIcons link until then: https://stadiaicons.web.app/

**Comment by ChristopherKlay** [comment]
Yep, this is most likely an issue with Stadia Enhanced and the new UI.

I was able to fix the menu issues due to Google rolling those out early, but until i get access to the new UI, i won't be able to fix the shortcuts. Sadly still on the old version, with just the navbar update :/
